### ISSUE TITLE
文章副标题

### ISSUE THREAD

**Issue by qiantao94** [fuzhouxxdong/hexo-theme-dxx#2]
主题不错，很喜欢！
但是请问如何才能显示首页的文章列表的副标题呢，看了半天源码，好像没有配置。

**Comment by fuzhouxxdong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    


要加
https://raw.githubusercontent.com/fuzhouxxdong/hexo-theme-dxx/demo/source/_posts/hello-world.md这个branches 是demohttps://github.com/fuzhouxxdong/hexo-theme-dxx/tree/demo

    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                


    在2018年5月30日 10:13，Salama<notifications@github.com> 写道： 


主题不错，很喜欢！
但是请问如何才能显示首页的文章列表的副标题呢，看了半天源码，好像没有配置。

**Comment by qiantao94** [comment]
谢谢🙏
这个主题支持评论吗，比如 disqus

**Comment by fuzhouxxdong** [comment]
这个可以自己加的，在post.pug 中可以搞一搞，最近忙公司项目没事搞了，等有时间会更新

**Comment by qiantao94** [comment]
OK, 期待你的更新，有空我也研究一下。
